import { useState } from 'react';
import { Lead, Area, Priority } from '../types';
import { priorities, todayIso } from '../utils/lead';
import { X } from 'lucide-react';
const empty=(area:Area):Lead=>({id:crypto.randomUUID(),area,company:'',contact:'',role:'',phone:'',mobile:'',email:'',website:'',street:'',zip:'',city:'',category:area==='kunden'?'PV':'Partner',source:'Kaltakquise',owner:'boris',status:'Neu',priority:'Mittel',note:'',nextAction:'Anrufen',dueDate:todayIso(),attempts:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export function LeadFormModal({mode,area,onClose,onSave}:{mode:'full'|'quick';area:Area;onClose:()=>void;onSave:(lead:Lead)=>void}){const [lead,setLead]=useState<Lead>(empty(area));const set=(k:keyof Lead,v:string|number)=>setLead(l=>({...l,[k]:v}));function submit(){if(!lead.company || !lead.phone){alert('Firma und Telefon sind Pflicht.');return;} onSave({...lead,updatedAt:new Date().toISOString()});onClose();}
 return <div className="modalOverlay"><div className="card modal"><div className="modalHead"><div><h2>{mode==='quick'?'⚡ Schneller Lead':'➕ Neuer Lead'}</h2><p className="muted">Direkt erfassen und sofort in die Telefon-Session übernehmen.</p></div><button className="btn" onClick={onClose}><X size={18}/></button></div>
 <div className="formGrid"><div className="field"><label>Bereich</label><select className="select" value={lead.area} onChange={e=>set('area',e.target.value)}><option value="kunden">Kunden-Leads</option><option value="netzwerk">Netzwerk</option></select></div><div className="field"><label>Kategorie</label><input className="input" value={lead.category} onChange={e=>set('category',e.target.value)} placeholder="PV, Dach, Partner..."/></div><div className="field"><label>Firma *</label><input className="input" value={lead.company} onChange={e=>set('company',e.target.value)} placeholder="Müller GmbH"/></div><div className="field"><label>Ansprechpartner</label><input className="input" value={lead.contact} onChange={e=>set('contact',e.target.value)} placeholder="Thomas Müller"/></div><div className="field"><label>Telefon *</label><input className="input" value={lead.phone} onChange={e=>set('phone',e.target.value)} placeholder="+49172..."/></div><div className="field"><label>E-Mail</label><input className="input" value={lead.email} onChange={e=>set('email',e.target.value)} placeholder="info@firma.de"/></div>{mode==='full'&&<><div className="field"><label>Ort</label><input className="input" value={lead.city} onChange={e=>set('city',e.target.value)} placeholder="Kiel"/></div><div className="field"><label>Webseite</label><input className="input" value={lead.website} onChange={e=>set('website',e.target.value)} placeholder="https://..."/></div><div className="field"><label>Leadquelle</label><select className="select" value={lead.source} onChange={e=>set('source',e.target.value)}><option>Kaltakquise</option><option>Google</option><option>Facebook</option><option>Instagram</option><option>Empfehlung</option><option>Messe</option><option>Website</option><option>Netzwerk</option></select></div><div className="field"><label>Priorität</label><select className="select" value={lead.priority} onChange={e=>set('priority',e.target.value as Priority)}>{priorities.map(p=><option key={p}>{p}</option>)}</select></div><div className="field" style={{gridColumn:'1/-1'}}><label>Notiz</label><textarea className="textarea" value={lead.note} onChange={e=>set('note',e.target.value)} placeholder="Kurze Info zum Kontakt..."/></div></>}
 </div><div style={{display:'flex',gap:10,justifyContent:'flex-end',marginTop:16}}><button className="btn" onClick={onClose}>Abbrechen</button><button className="btn btnPrimary" onClick={submit}>Speichern</button></div></div></div>}
